// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9cJ8nrSOqk3PP6ww4w6PM5SJleIMe3o8',
    appId: '1:373530031606:web:05f0d03a5c5a509cddc3d7',
    messagingSenderId: '373530031606',
    projectId: 'ushopiaapp',
    authDomain: 'ushopiaapp.firebaseapp.com',
    storageBucket: 'ushopiaapp.firebasestorage.app',
    measurementId: 'G-DV0DKE19H4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKyC4nIQ9VpHn5gmKNZSEwu9BMl0oZGws',
    appId: '1:373530031606:android:1bcaa09f0a8f2705ddc3d7',
    messagingSenderId: '373530031606',
    projectId: 'ushopiaapp',
    storageBucket: 'ushopiaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2-YZjDXwqlbFK5keJ6_RJ3N5RHGReD6Y',
    appId: '1:373530031606:ios:a35dfe8480ae9590ddc3d7',
    messagingSenderId: '373530031606',
    projectId: 'ushopiaapp',
    storageBucket: 'ushopiaapp.firebasestorage.app',
    iosBundleId: 'com.example.tStore',
  );
}
