// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG06sR6__CdJV7CFYg0nZDTOqOztGAbyE',
    appId: '1:395731786934:web:0f05908109e4c87c3e5a17',
    messagingSenderId: '395731786934',
    projectId: 'ushopia-95726',
    authDomain: 'ushopia-95726.firebaseapp.com',
    storageBucket: 'ushopia-95726.firebasestorage.app',
    measurementId: 'G-18XRR5SSZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWXwb4xGIxovO1I7ca-P36RM1ZNgR6tOU',
    appId: '1:395731786934:android:3b5cb36a1f49ae733e5a17',
    messagingSenderId: '395731786934',
    projectId: 'ushopia-95726',
    storageBucket: 'ushopia-95726.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARbvWmMCt4hyGImcMwhEcjajXjUEp--Qk',
    appId: '1:395731786934:ios:d287e2456bd636ca3e5a17',
    messagingSenderId: '395731786934',
    projectId: 'ushopia-95726',
    storageBucket: 'ushopia-95726.firebasestorage.app',
    iosBundleId: 'com.example.tStore',
  );

}